SET search_path TO ai_registration;

COMMENT ON TABLE knowledge_document IS 'RAG 知识文档主表，记录原始知识源、版本和发布状态。';
COMMENT ON COLUMN knowledge_document.id IS '知识文档主键。';
COMMENT ON COLUMN knowledge_document.namespace IS '知识命名空间，用于隔离分诊、导诊、挂号政策等语料。';
COMMENT ON COLUMN knowledge_document.source_id IS '外部知识源 ID，同一 namespace 内用于幂等更新。';
COMMENT ON COLUMN knowledge_document.source_name IS '知识源名称。';
COMMENT ON COLUMN knowledge_document.document_type IS '文档类型，例如 POLICY、FAQ、DEPARTMENT_GUIDE。';
COMMENT ON COLUMN knowledge_document.title IS '文档标题。';
COMMENT ON COLUMN knowledge_document.content_sha256 IS '原始内容 SHA-256 摘要，用于去重和变更检测。';
COMMENT ON COLUMN knowledge_document.version IS '知识版本号。';
COMMENT ON COLUMN knowledge_document.status IS '知识发布状态：DRAFT 草稿，ACTIVE 生效，ARCHIVED 归档。旧 DISABLED 应按 DRAFT 处理。';
COMMENT ON COLUMN knowledge_document.metadata IS '文档级扩展元数据，JSON 格式。';
COMMENT ON COLUMN knowledge_document.created_at IS '记录创建时间。';
COMMENT ON COLUMN knowledge_document.updated_at IS '记录最后更新时间。';

COMMENT ON TABLE knowledge_chunk IS 'RAG 知识切片表，保存可检索文本、向量和检索元数据。';
COMMENT ON COLUMN knowledge_chunk.id IS '知识切片主键。';
COMMENT ON COLUMN knowledge_chunk.document_id IS '所属知识文档主键，关联 knowledge_document。';
COMMENT ON COLUMN knowledge_chunk.namespace IS '知识命名空间，冗余保存便于检索过滤。';
COMMENT ON COLUMN knowledge_chunk.chunk_index IS '文档内切片序号。';
COMMENT ON COLUMN knowledge_chunk.chunk_type IS '切片类型，默认 TEXT。';
COMMENT ON COLUMN knowledge_chunk.title IS '切片标题或小节标题。';
COMMENT ON COLUMN knowledge_chunk.content IS '切片正文内容。';
COMMENT ON COLUMN knowledge_chunk.token_count IS '切片估算 token 数。';
COMMENT ON COLUMN knowledge_chunk.metadata IS 'RAG 切片元数据。分诊使用 departmentCode/departmentName/emergency，导诊使用 sourceId/sourceName，挂号政策使用 policyType/actionTag/validFrom/validTo。';
COMMENT ON COLUMN knowledge_chunk.embedding_model IS '生成该切片向量的模型名称。';
COMMENT ON COLUMN knowledge_chunk.embedding_dimensions IS '生成该切片向量的维度。当前 text-embedding-v2 与库表统一为 1536 维。';
COMMENT ON COLUMN knowledge_chunk.embedding IS 'pgvector 向量字段，当前 schema 为 vector(1536)。';
COMMENT ON COLUMN knowledge_chunk.enabled IS '切片是否参与在线检索。';
COMMENT ON COLUMN knowledge_chunk.created_at IS '记录创建时间。';
COMMENT ON COLUMN knowledge_chunk.updated_at IS '记录最后更新时间。';

COMMENT ON TABLE knowledge_ingest_job IS '知识入库任务表，记录知识导入、切片、向量化的执行结果。';
COMMENT ON COLUMN knowledge_ingest_job.id IS '知识入库任务主键。';
COMMENT ON COLUMN knowledge_ingest_job.namespace IS '知识命名空间。';
COMMENT ON COLUMN knowledge_ingest_job.source_id IS '外部知识源 ID。';
COMMENT ON COLUMN knowledge_ingest_job.source_name IS '知识源名称。';
COMMENT ON COLUMN knowledge_ingest_job.document_id IS '本次任务生成或更新的知识文档主键。';
COMMENT ON COLUMN knowledge_ingest_job.status IS '入库任务状态：PENDING、RUNNING、SUCCEEDED、PARTIALLY_FAILED、FAILED。';
COMMENT ON COLUMN knowledge_ingest_job.embedding_model IS '本次入库使用的向量模型名称。';
COMMENT ON COLUMN knowledge_ingest_job.embedding_dimensions IS '本次入库使用的向量维度。';
COMMENT ON COLUMN knowledge_ingest_job.document_count IS '本次处理的文档数量。';
COMMENT ON COLUMN knowledge_ingest_job.chunk_count IS '本次生成或更新的切片数量。';
COMMENT ON COLUMN knowledge_ingest_job.error_message IS '任务失败或部分失败时的错误摘要。';
COMMENT ON COLUMN knowledge_ingest_job.metadata IS '任务扩展元数据，JSON 格式。';
COMMENT ON COLUMN knowledge_ingest_job.started_at IS '任务开始时间。';
COMMENT ON COLUMN knowledge_ingest_job.finished_at IS '任务结束时间。';

COMMENT ON TABLE knowledge_retrieval_log IS 'RAG 检索日志表，记录每次检索的入参、命中和耗时。';
COMMENT ON COLUMN knowledge_retrieval_log.id IS '检索日志主键。';
COMMENT ON COLUMN knowledge_retrieval_log.trace_id IS '链路追踪 ID。';
COMMENT ON COLUMN knowledge_retrieval_log.chat_id IS '关联的对话会话 ID。';
COMMENT ON COLUMN knowledge_retrieval_log.namespace IS '知识命名空间。';
COMMENT ON COLUMN knowledge_retrieval_log.corpus_name IS '检索语料名称。';
COMMENT ON COLUMN knowledge_retrieval_log.query_text IS '检索查询文本。';
COMMENT ON COLUMN knowledge_retrieval_log.top_k IS '请求返回的最大命中数量。';
COMMENT ON COLUMN knowledge_retrieval_log.min_score IS '最小相似度阈值。';
COMMENT ON COLUMN knowledge_retrieval_log.status IS '检索状态，例如 HIT、MISS、EMBEDDING_UNAVAILABLE、RETRIEVAL_ERROR。';
COMMENT ON COLUMN knowledge_retrieval_log.hit_count IS '命中切片数量。';
COMMENT ON COLUMN knowledge_retrieval_log.best_hit_id IS '最高分命中切片 ID。';
COMMENT ON COLUMN knowledge_retrieval_log.best_score IS '最高命中相似度分数。';
COMMENT ON COLUMN knowledge_retrieval_log.latency_ms IS '检索耗时，单位毫秒。';
COMMENT ON COLUMN knowledge_retrieval_log.error_message IS '检索失败时的错误摘要。';
COMMENT ON COLUMN knowledge_retrieval_log.hit_ids IS '命中切片 ID 列表，JSON 数组。';
COMMENT ON COLUMN knowledge_retrieval_log.created_at IS '检索日志创建时间。';

COMMENT ON TABLE registration_workflow_execution_log IS '挂号工作流执行日志，记录编排节点、确认点和执行状态。';
COMMENT ON COLUMN registration_workflow_execution_log.id IS '工作流执行日志主键。';
COMMENT ON COLUMN registration_workflow_execution_log.execution_id IS '一次挂号工作流执行的唯一标识。';
COMMENT ON COLUMN registration_workflow_execution_log.confirmation_id IS '用户确认检查点 ID，可为空。';
COMMENT ON COLUMN registration_workflow_execution_log.trace_id IS '链路追踪 ID。';
COMMENT ON COLUMN registration_workflow_execution_log.chat_id IS '关联的对话会话 ID。';
COMMENT ON COLUMN registration_workflow_execution_log.user_id IS '发起流程的平台用户唯一标识。';
COMMENT ON COLUMN registration_workflow_execution_log.workflow_id IS '工作流定义标识。';
COMMENT ON COLUMN registration_workflow_execution_log.intent IS '挂号意图，例如 CREATE、QUERY、CANCEL、RESCHEDULE。';
COMMENT ON COLUMN registration_workflow_execution_log.node_id IS '当前执行节点 ID。';
COMMENT ON COLUMN registration_workflow_execution_log.status IS '节点执行状态，例如 STARTED、SUCCEEDED、FAILED、WAITING_CONFIRMATION。';
COMMENT ON COLUMN registration_workflow_execution_log.payload IS '节点输入输出和上下文快照，JSON 格式。';
COMMENT ON COLUMN registration_workflow_execution_log.created_at IS '工作流执行日志创建时间。';
